name: Build and Push to Docker Hub

on:
  # Run when we click the Run Job button on GitHub.
  workflow_dispatch:
  # Run when there is a new Release (has a tag).
  push:
    tags: ['**']    # Match any tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Update the version/tag.
      - name: Update version
        run: sed -i 's/__version__ = "0.0.0-dev"/__version__ = "'"${GITHUB_REF##*/}"'"/g' src/__init__.py

      # Build and push the Docker image
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quantconnect/mcp-server:${{ github.ref_name }}
            quantconnect/mcp-server:latest
